/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connector.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brian R
 */
public class admin1 extends javax.swing.JPanel {

    /**
     * Creates new form admin1
     */
    Connection connection = config.Connection();
    Statement statement;
    ResultSet resultSet;
    
    public admin1() {
        initComponents();
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnReset() {
        return btnReset;
    }

    public JTextField getIdAdmin1() {
        return idAdmin1;
    }

    public void setIdAdmin1(String idAdmin1) {
        this.idAdmin1.setText(idAdmin1);
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnUbah() {
        return btnUbah;
    }

    public JTextField getNameAdmin1() {
        return nameAdmin1;
    }

    public JTextField getPassAdmin1() {
        return passAdmin1;
    }

    public JTable getTable_users() {
        return table_users;
    }

    public JTextField getUserAdmin1() {
        return userAdmin1;
    }

    public void setNameAdmin1(String nameAdmin1) {
        this.nameAdmin1.setText(nameAdmin1);
    }

    public void setPassAdmin1(String passAdmin1) {
        this.passAdmin1.setText(passAdmin1);
    }

    public void setTable_users(DefaultTableModel tabel) {
        this.table_users.setModel(tabel);
    }

    public void setTabel(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }

    public void setUserAdmin1(String userAdmin1) {
        this.userAdmin1.setText(userAdmin1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_users = new javax.swing.JTable();
        nameAdmin1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userAdmin1 = new javax.swing.JTextField();
        passAdmin1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        idAdmin1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(690, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nama", "Username", "Password"
            }
        ));
        table_users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_usersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_users);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 70, 390, 450));
        add(nameAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, 140, -1));

        jLabel1.setText("Nama");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jLabel2.setText("Username");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));
        add(userAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 140, -1));
        add(passAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 270, 140, -1));

        jLabel3.setText("Password");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        btnSimpan.setText("Simpan");
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        btnReset.setText("Reset");
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, -1, -1));

        btnUbah.setText("Ubah");
        add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, -1, -1));

        btnHapus.setText("Hapus");
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 360, -1, -1));

        jLabel4.setText("Pencarian");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, -1, -1));
        add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 30, 170, -1));

        idAdmin1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAdmin1ActionPerformed(evt);
            }
        });
        add(idAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 140, -1));

        jLabel5.setText("Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void idAdmin1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAdmin1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAdmin1ActionPerformed

    private void table_usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_usersMouseClicked
        int baris = table_users.getSelectedRow();
        idAdmin1.setText(table_users.getModel().getValueAt(baris, 0).toString());
        nameAdmin1.setText(table_users.getModel().getValueAt(baris, 1).toString());
        userAdmin1.setText(table_users.getModel().getValueAt(baris, 2).toString());
        passAdmin1.setText(table_users.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_table_usersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JTextField idAdmin1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField nameAdmin1;
    private javax.swing.JTextField passAdmin1;
    private javax.swing.JTable table_users;
    private javax.swing.JTextField userAdmin1;
    // End of variables declaration//GEN-END:variables
}
