/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connector.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brian R
 */
public class admin2 extends javax.swing.JPanel {

    /**
     * Creates new form admin2
     */
//    Connection connection = config.Connection();
//    Statement statement;
//    ResultSet resultSet;
    public admin2() {
        initComponents();
//        tampilBarang();
        
    }

    public JTable getTable_barang() {
        return table_barang;
    }

    public void setTable_barang(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }
    
//    private void tampilBarang() {
//        
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_barang = new javax.swing.JTable();
        cari_barang = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_barang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Barang", "Nama Barang", "Jumlah Stok", "Harga Barang"
            }
        ));
        jScrollPane1.setViewportView(table_barang);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 670, 440));

        cari_barang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_barangKeyPressed(evt);
            }
        });
        add(cari_barang, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 170, -1));

        jLabel1.setText("Pencarian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void cari_barangKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_barangKeyPressed
//        DefaultTableModel model = new DefaultTableModel();
//        model.addColumn("Kode Barang");
//        model.addColumn("Nama Barang");
//        model.addColumn("Jumlah Stok");
//        model.addColumn("Harga");
//        try {
//            String sql = "select * from barang where kode_barang like '%" + cari_barang.getText() + "%' or nama_barang like '%" + cari_barang.getText() + "%' or jumlah_stok like '%" + cari_barang.getText() + "%' or harga like '%" + cari_barang.getText() + "%'";
//            statement = connection.createStatement();
//            resultSet = statement.executeQuery(sql);
//
//            int no = 0;
//            while (resultSet.next()) {
//                no++;
//                model.addRow(new Object[]{
//                    resultSet.getString("kode_barang"), resultSet.getString("nama_barang"), resultSet.getString("jumlah_stok"), resultSet.getString("harga")
//                });
//            }
//            table_barang.setModel(model);
//        } catch (Exception e) {
//            System.out.println(e.getMessage());
//        }
    }//GEN-LAST:event_cari_barangKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari_barang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_barang;
    // End of variables declaration//GEN-END:variables
}
