/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connector.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.jdbc.JDBCCategoryDataset;

/**
 *
 * @author Brian R
 */
public class admin3 extends javax.swing.JPanel {

    Connection connection = config.Connection();
    Statement statement;
    ResultSet resultSet;

    public admin3() {
        initComponents();
//        tampilBarang();
    }

    private void tampilBarang() {
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Nama Toko");
        model.addColumn("Nama Barang");
        model.addColumn("Tanggal");
        model.addColumn("Jumlah");
        try {
            String sql = "SELECT\n" +
"  `e-waralaba`.barang.nama_barang,\n" +
"  `e-waralaba`.users.username,\n" +
"  `e-waralaba`.tb_penjualan.jumlah_penjualan,\n" +
"  `e-waralaba`.tb_penjualan.tanggal\n" +
"FROM\n" +
"  `e-waralaba`.users\n" +
"  INNER JOIN `e-waralaba`.tb_barangtokoo ON `e-waralaba`.tb_barangtokoo.id = `e-waralaba`.users.id\n" +
"  INNER JOIN `e-waralaba`.tb_penjualan ON `e-waralaba`.tb_penjualan.kode_barang =\n" +
"    `e-waralaba`.tb_barangtokoo.kode_barang\n" +
"  INNER JOIN `e-waralaba`.barang ON `e-waralaba`.tb_barangtokoo.kode_barang = `e-waralaba`.barang.kode_barang";
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);

            int no = 0;
            while (resultSet.next()) {
                no++;
                model.addRow(new Object[]{
                    resultSet.getString("users.username"), resultSet.getString("barang.nama_barang"), resultSet.getString("tanggal"), resultSet.getString("jumlah_penjualan")
                });
            }
            table_toko.setModel(model);
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_toko = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(690, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_toko.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Toko", "Nama Barang", "Tanggal", "Jumlah Terjual"
            }
        ));
        jScrollPane1.setViewportView(table_toko);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 670, 330));
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 40, 170, -1));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnChart.png"))); // NOI18N
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 430, -1, -1));

        jLabel1.setText("Pencarian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            String sql = "SELECT\n" +
"  `e-waralaba`.barang.nama_barang,\n" +
"  `e-waralaba`.tb_penjualan.jumlah_penjualan\n" +
"FROM\n" +
"  `e-waralaba`.users\n" +
"  INNER JOIN `e-waralaba`.tb_barangtokoo ON `e-waralaba`.tb_barangtokoo.id = `e-waralaba`.users.id\n" +
"  INNER JOIN `e-waralaba`.tb_penjualan ON `e-waralaba`.tb_penjualan.kode_barang =\n" +
"    `e-waralaba`.tb_barangtokoo.kode_barang\n" +
"  INNER JOIN `e-waralaba`.barang ON `e-waralaba`.tb_barangtokoo.kode_barang = `e-waralaba`.barang.kode_barang";
            JDBCCategoryDataset dataset = new JDBCCategoryDataset(config.connection, sql);
            statement = connection.createStatement();
            resultSet = statement.executeQuery(sql);
            JFreeChart chart = ChartFactory.createLineChart("Chart", "Nama Barang", "Jumlah Penjualan", dataset, PlotOrientation.VERTICAL, false, true, true);
            BarRenderer render = null;
            CategoryPlot plot = null;
            render = new BarRenderer();
            ChartFrame frame = new ChartFrame("Chart", chart);
            frame.setVisible(true);
            frame.setSize(400, 650);
            frame.setLocationRelativeTo(null);
        } catch (Exception e) {
            e.getMessage();
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTable table_toko;
    // End of variables declaration//GEN-END:variables
}
