/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import connector.config;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.HashMap;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.m_gudang2;

/**
 *
 * @author Brian R
 */
public class gudang2 extends javax.swing.JPanel {

    Connection connection = config.Connection();
    Statement statement;
    ResultSet resultSet;
    public static int id[];
    public static int kode_barang[];
    m_gudang2 model;

    public gudang2() {
        initComponents();
        DropToko();
        DropBarang();
    }

    public JTextField getId_barangtoko() {
        return id_barangtoko;
    }

    public void setId_barangtoko(String id_barangtoko) {
        this.id_barangtoko.setText(id_barangtoko);
    }

    public JButton getBtnHapus() {
        return btnHapus;
    }

    public JButton getBtnReset() {
        return btnReset;
    }

    public JButton getBtnSimpan() {
        return btnSimpan;
    }

    public JButton getBtnUbah() {
        return btnUbah;
    }

    public JComboBox getDdBarang() {
        return ddBarang;
    }

    public JComboBox getDdUsers() {
        return ddUsers;
    }

    public void setDdUsers(String ddUsers) {
        this.ddUsers.addItem(ddUsers);
    }

    public void setDdBarang(String ddBarang) {
        this.ddBarang.addItem(ddBarang);
    }

    public JTextField getJumlah_field() {
        return jumlah_field;
    }

    public void setJumlah_field(String jumlah_field) {
        this.jumlah_field.setText(jumlah_field);
    }

    public JTable getTable_gudang2() {
        return table_gudang2;
    }

    public void setTable_gudang2(DefaultTableModel tabel) {
        this.table_gudang2.setModel(tabel);
    }

    public void setTabel(JTable t, DefaultTableModel tabel) {
        t.setModel(tabel);
    }

    public void comboUser() {
        HashMap<String, Integer> map = model.comboUsers();
        for (String s : map.keySet()) {
            setDdUsers(s);
        }
    }

    public void comboBarang() {
        HashMap<String, Integer> map = model.comboBarang();
        for (String s : map.keySet()) {
            setDdBarang(s);
        }
    }

    private void DropToko() {
//        try {
//            String sql = "select * from users where status = 3 order by username";
//            statement = connection.prepareStatement(sql);
//            resultSet = statement.executeQuery(sql);
//
//            while (resultSet.next()) {
//                String users = resultSet.getString("users.username");
//                ddUsers.addItem(users);
//            }
//        } catch (Exception e) {
//            e.getMessage();
//        }
    }

    private void DropBarang() {
//        try {
//            String sql = "select * from barang order by nama_barang";
//            statement = connection.prepareStatement(sql);
//            resultSet = statement.executeQuery(sql);
//
//            while (resultSet.next()) {
//                String barang = resultSet.getString("barang.nama_barang");
//                ddBarang.addItem(barang);
//            }
//        } catch (Exception e) {
//            e.getMessage();
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table_gudang2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        ddUsers = new javax.swing.JComboBox<>();
        ddBarang = new javax.swing.JComboBox<>();
        jumlah_field = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnUbah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        id_barangtoko = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(690, 530));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table_gudang2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Id Toko", "Id Barang", "Jumlah"
            }
        ));
        table_gudang2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_gudang2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_gudang2);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, 400, 440));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 180, -1));

        jLabel1.setText("Pencarian");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 30, -1, -1));

        ddUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddUsersActionPerformed(evt);
            }
        });
        add(ddUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 100, -1));

        add(ddBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 100, -1));

        jumlah_field.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlah_fieldActionPerformed(evt);
            }
        });
        add(jumlah_field, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 110, -1));

        jLabel2.setText("Toko");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jLabel3.setText("Barang");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, -1, -1));

        jLabel4.setText("Jumlah");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        btnSimpan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnSimpan.png"))); // NOI18N
        btnSimpan.setBorderPainted(false);
        btnSimpan.setContentAreaFilled(false);
        add(btnSimpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 130, -1));

        btnUbah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnUbah.png"))); // NOI18N
        btnUbah.setBorderPainted(false);
        btnUbah.setContentAreaFilled(false);
        add(btnUbah, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 320, 130, -1));

        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnHapus.png"))); // NOI18N
        btnHapus.setBorderPainted(false);
        btnHapus.setContentAreaFilled(false);
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });
        add(btnHapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 130, -1));

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnReset.png"))); // NOI18N
        btnReset.setBorderPainted(false);
        btnReset.setContentAreaFilled(false);
        add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 130, -1));

        jLabel5.setText("Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));
        add(id_barangtoko, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, 100, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jumlah_fieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlah_fieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlah_fieldActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void ddUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddUsersActionPerformed

    }//GEN-LAST:event_ddUsersActionPerformed

    private void table_gudang2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_gudang2MouseClicked
        int baris = table_gudang2.getSelectedRow();
        id_barangtoko.setText(table_gudang2.getModel().getValueAt(baris, 0).toString());
        jumlah_field.setText(table_gudang2.getModel().getValueAt(baris, 3).toString());
    }//GEN-LAST:event_table_gudang2MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JComboBox<String> ddBarang;
    private javax.swing.JComboBox<String> ddUsers;
    private javax.swing.JTextField id_barangtoko;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jumlah_field;
    private javax.swing.JTable table_gudang2;
    // End of variables declaration//GEN-END:variables
}
