/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;

/**
 *
 * @author Brian R
 */
public class v_Admin extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout();

    admin1 a1;
    admin2 a2;
    admin3 a3;

    public v_Admin(admin1 a1, admin2 a2, admin3 a3) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.a1 = a1;
        this.a2 = a2;
        this.a3 = a3;
        
        panelAdmin.setLayout(layout);
        panelAdmin.add(a1);
        panelAdmin.add(a2);
        panelAdmin.add(a3);
        
        this.a1.setVisible(true);
        this.a2.setVisible(false);
        this.a3.setVisible(false);
        
        
        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Login a = new Login();
                a.setVisible(true);
                dispose();
            }
        });

    }
    private void setColor(JPanel panel){
        panel.setBackground(new Color (245,87,108));
    }
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(247,176,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelAdmin = new javax.swing.JPanel();
        adminUsers = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        adminGudang = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();
        adminToko = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        panelAdmin.setPreferredSize(new java.awt.Dimension(690, 530));

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(panelAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 690, -1));

        adminUsers.setBackground(new java.awt.Color(245, 87, 108));
        adminUsers.setPreferredSize(new java.awt.Dimension(260, 47));
        adminUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminUsersMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USERS");

        javax.swing.GroupLayout adminUsersLayout = new javax.swing.GroupLayout(adminUsers);
        adminUsers.setLayout(adminUsersLayout);
        adminUsersLayout.setHorizontalGroup(
            adminUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminUsersLayout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel2)
                .addContainerGap(108, Short.MAX_VALUE))
        );
        adminUsersLayout.setVerticalGroup(
            adminUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminUsersLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        getContentPane().add(adminUsers, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, -1, -1));

        adminGudang.setBackground(new java.awt.Color(247, 176, 255));
        adminGudang.setPreferredSize(new java.awt.Dimension(260, 47));
        adminGudang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminGudangMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("GUDANG");

        javax.swing.GroupLayout adminGudangLayout = new javax.swing.GroupLayout(adminGudang);
        adminGudang.setLayout(adminGudangLayout);
        adminGudangLayout.setHorizontalGroup(
            adminGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminGudangLayout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabel3)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        adminGudangLayout.setVerticalGroup(
            adminGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminGudangLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        getContentPane().add(adminGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, -1, -1));

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLogout.png"))); // NOI18N
        btnLogout.setContentAreaFilled(false);
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, -1, -1));

        adminToko.setBackground(new java.awt.Color(247, 176, 255));
        adminToko.setPreferredSize(new java.awt.Dimension(260, 47));
        adminToko.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                adminTokoMousePressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TOKO");

        javax.swing.GroupLayout adminTokoLayout = new javax.swing.GroupLayout(adminToko);
        adminToko.setLayout(adminTokoLayout);
        adminTokoLayout.setHorizontalGroup(
            adminTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTokoLayout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(jLabel4)
                .addContainerGap(115, Short.MAX_VALUE))
        );
        adminTokoLayout.setVerticalGroup(
            adminTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminTokoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(adminToko, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgAdmin.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminUsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminUsersMousePressed
        setColor(adminUsers);
        resetColor(adminGudang);
        resetColor(adminToko);
        this.a1.setVisible(true);
        this.a2.setVisible(false);
        this.a3.setVisible(false);
    }//GEN-LAST:event_adminUsersMousePressed

    private void adminGudangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminGudangMousePressed
        setColor(adminGudang);
        resetColor(adminUsers);
        resetColor(adminToko);
        this.a1.setVisible(false);
        this.a2.setVisible(true);
        this.a3.setVisible(false);
    }//GEN-LAST:event_adminGudangMousePressed

    private void adminTokoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminTokoMousePressed
        setColor(adminToko);
        resetColor(adminGudang);
        resetColor(adminUsers);
        this.a1.setVisible(false);
        this.a2.setVisible(false);
        this.a3.setVisible(true);
    }//GEN-LAST:event_adminTokoMousePressed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Admin(a1,a2,a3).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminGudang;
    private javax.swing.JPanel adminToko;
    private javax.swing.JPanel adminUsers;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel panelAdmin;
    // End of variables declaration//GEN-END:variables
}
