/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.c_gudang1;
import controller.c_login;
import java.awt.Color;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JPanel;
import model.m_login;

/**
 *
 * @author Brian R
 */
public class v_Gudang extends javax.swing.JFrame {
    
    GridBagLayout layout = new GridBagLayout();
    
    gudang1 g1 = new gudang1();
    gudang2 g2 = new gudang2();
    
    public v_Gudang(gudang1 g1, gudang2 g2) {
        initComponents();
        btnLogout.setBackground(new Color(0, 0, 0, 0));
        this.setLocationRelativeTo(null);
        this.g1 = g1;
        this.g2 = g2;
//        g1 = new gudang1();
//        g2 = new gudang2();
        
        panelGudang.setLayout(layout);
        panelGudang.add(this.g1);
        panelGudang.add(this.g2);
        
        this.g1.setVisible(true);
        this.g2.setVisible(false);
        
        btnLogout.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                m_login m = new m_login();
                Login v = new Login();
                c_login c = new c_login(m, v);
                dispose();
            }
        });
    }
    private void setColor(JPanel panel){
        panel.setBackground(new Color (245,87,108));
    }
    private void resetColor(JPanel panel){
        panel.setBackground(new Color(247,176,255));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        gudangBarang = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        panelGudang = new javax.swing.JPanel();
        gudangStok = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/btnLogout.png"))); // NOI18N
        btnLogout.setContentAreaFilled(false);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 150, -1));

        gudangBarang.setBackground(new java.awt.Color(245, 87, 108));
        gudangBarang.setRequestFocusEnabled(false);
        gudangBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gudangBarangMousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Data Barang");

        javax.swing.GroupLayout gudangBarangLayout = new javax.swing.GroupLayout(gudangBarang);
        gudangBarang.setLayout(gudangBarangLayout);
        gudangBarangLayout.setHorizontalGroup(
            gudangBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gudangBarangLayout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel2)
                .addContainerGap(83, Short.MAX_VALUE))
        );
        gudangBarangLayout.setVerticalGroup(
            gudangBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gudangBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(gudangBarang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 260, 50));

        panelGudang.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelGudangLayout = new javax.swing.GroupLayout(panelGudang);
        panelGudang.setLayout(panelGudangLayout);
        panelGudangLayout.setHorizontalGroup(
            panelGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        panelGudangLayout.setVerticalGroup(
            panelGudangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 530, Short.MAX_VALUE)
        );

        getContentPane().add(panelGudang, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 690, 530));

        gudangStok.setBackground(new java.awt.Color(247, 176, 255));
        gudangStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                gudangStokMousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Bebas Neue", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Data PENGIRIMAN BARANG");

        javax.swing.GroupLayout gudangStokLayout = new javax.swing.GroupLayout(gudangStok);
        gudangStok.setLayout(gudangStokLayout);
        gudangStokLayout.setHorizontalGroup(
            gudangStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gudangStokLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        gudangStokLayout.setVerticalGroup(
            gudangStokLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gudangStokLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(gudangStok, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 260, 50));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Admin Gudang");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Brian Rizqi");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bgGudang.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed

    }//GEN-LAST:event_btnLogoutActionPerformed

    private void gudangBarangMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangBarangMousePressed
        setColor(gudangBarang);
        resetColor(gudangStok);
        g1.setVisible(true);
        g2.setVisible(false);
    }//GEN-LAST:event_gudangBarangMousePressed

    private void gudangStokMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gudangStokMousePressed
        setColor(gudangStok);
        resetColor(gudangBarang);
        g1.setVisible(false);
        g2.setVisible(true);
    }//GEN-LAST:event_gudangStokMousePressed

    /**
     * @param args the command line arguments
     */
    public void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v_Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v_Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v_Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v_Gudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v_Gudang(g1,g2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel gudangBarang;
    private javax.swing.JPanel gudangStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panelGudang;
    // End of variables declaration//GEN-END:variables
}
